apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-rg"
  annotations:
    github.com/project-slug: hirveakshata/azure-rg-template # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  title: "backstage-rg" # you can give any title
  description: "Testing" # Change Description accordingly
 # tags: 
spec:
  type: Infrastructure services
  owner: user:guest
  lifecycle: "Experimental"

